language:
  - node_js

node_js:
  - "8.0.0"

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - npm start
  - npm test

notifications:
  slack:
    rooms:
      - tna-digital:C2GnodnLsxhwwGvr0xAcajzc#code-builds